### PR TITLE
calculate auto margins for absolutely positioned elements

### PR DESCRIPTION
**Pull request by NuclearCookie**

### CODE REVIEW

**Comment by crazyjul** [comment]
I don't agree with this MR. margin should not be auto computed on absolute-positioned element : 
http://stackoverflow.com/questions/9998260/css-absolute-position-wont-work-with-margin-leftauto-margin-right-auto

**Comment by crazyjul** [comment]
This looks perfect, but I wonder where vertical margins are managed. Does the vertical code require the same fix?

**Comment by NuclearCookie** [comment]
I don't know. I couldn't find it at a first glance. The method name implies it would do it, but it does not. Confusing :confused:

**Comment by crazyjul** [comment]
Ok, let's keep this in mind

**Pull request merged**
