### PR TITLE
fixed box memory leak

### PR DESCRIPTION
**Pull request by NuclearCookie**

### CODE REVIEW

**Comment by crazyjul** [comment]
I don't think it fixes anything. What makes you believe the default generated destructor would not do its job?

**Comment by NuclearCookie** [comment]
You're right, I copied it from the base repository, but `litehtml:;box` has been refactored there and does not inherit from object anymore.

**Comment by crazyjul** [comment]
Which btw was a totally valid decision

**Comment by NuclearCookie** [comment]
Yes, we should really take the time to get up to date with the upstream again

**Pull request closed without merging**
